PARALLEL_JOBS = "8"
SYSTEM_INSTALLATION = false
BOOTLOADER = "grub"
COUNTRY_ISO = "CA"
FILE_SYSTEM_TYPE = "ext4"
FORMAT_TYPE = "ext4"
INSTALL_DEVICE = "nvme0n1"
DEVICE = "/dev/vda"
PARTITION_BIOSBOOT="/dev/vda"
PARTITION_EFI = "/dev/vda2"
PARTITION_ROOT = "/dev/vda3"
PARTITION_ROOT_ENC = "/dev/mapper/cryptroot"
PARTITION_HOME = "/dev/vda4"
PARTITION_HOME_ENC = "/dev/mapper/crypthome"
PARTITION_SWAP = "/dev/vda5"
MOUNT_OPTIONS = "noatime,compress=zstd,ssd,commit=120"
LOCALE = "en_US.UTF-8"
TIMEZONE = "America/Toronto"
KEYMAP = "us"
USERNAME = "ssnow"
PASSWORD = "changeme"
HOSTNAME = "arch"
MICROCODE = "amd"
GPU = "amd"
GPU_DRIVER = "amdgpu"
TERMINAL = "alacritty"
SHELL = "bash"
EDITOR = "neovim"
DESKTOP_ENVIRONMENT = "gnome"
SUBVOLUMES = "@home,@var,@tmp,@.snapshots"
LUKS_PASSWORD = "changeme"
LUKS = false
SWAP = false
SWAP_SIZE = "4"
ROOT_SIZE = "32"
HOME = false
BIOS_TYPE = "hybrid"
CPU_VENDOR = "amd"
GPU_VENDOR = "amd"
INITRD_MICROCODE = "amd-ucode.img"
RSA_KEY_DIR = "$HOME/.config/arch-install"
RSA_PRIVATE_KEY_PATH = "$HOME/.config/arch-install/private_key.pem"
RSA_PUBLIC_KEY_PATH = "$HOME/.config/arch-install/public_key.pem"
