PARALLEL_JOBS = "8"
SYSTEM_INSTALLATION = false
COUNTRY_ISO = "CA"
BIOS_TYPE = "hybrid"
FILE_SYSTEM_TYPE = "btrfs"
FORMAT_TYPE = "btrfs"
INSTALL_DEVICE = ""
DEVICE = ""
PARTITION_BOOT=""
PARTITION_EFI = ""
PARTITION_ROOT = ""
PARTITION_HOME = ""
PARTITION_SWAP = ""
SUBVOLUMES = "@home,@var,@.snapshots"
MOUNT_OPTIONS = "noatime,compress=zstd,ssd,commit=120"
LUKS = false
LUKS_PASSWORD = "changeme"
SWAP = false
EFI_SIZE = "1024"
SWAP_SIZE = "4"
ROOT_SIZE = "32"
HOME = false
LOCALE = "en_US.UTF-8"
TIMEZONE = "America/Toronto"
KEYMAP = "us"
USERNAME = "ssnow"
PASSWORD = "changeme"
HOSTNAME = "arch"
MICROCODE = "amd"
INITRD_MICROCODE = "amd-ucode.img"
TERMINAL = "alacritty"
SHELL = "bash"
EDITOR = "nvim"
DESKTOP_ENVIRONMENT = "gnome"
CPU_VENDOR = "amd"
GPU_VENDOR = "amd"
GPU = "amd"
GPU_DRIVER = "amdgpu"
THEME = "nordic"
