[stages]
"1-pre" = ["pre-setup.sh", "run-checks.sh"]
"2-drive" = ["partition-btrfs.sh", "format-btrfs.sh", "partition-ext4.sh", "format-ext4.sh"]
"3-base" = ["bootstrap-pkgs.sh", "generate-fstab.sh"]
"4-post" = ["system-config.sh", "system-pkgs.sh", "terminal.sh"]
"5-desktop" = ["gnome.sh", "kde.sh", "cosmic.sh", "dwm.sh", "none.sh"]
"6-final" = ["last-cleanup.sh"]
"7-post-optional" = ["post-setup.sh"]
